#!C:\Users\pacif\OneDrive\Desktop\projects\img_color_reader\public\.env\Scripts\python.exe

from dipy.workflows.flow_runner import run_flow
from dipy.workflows.denoise import Patch2SelfFlow


if __name__ == "__main__":
    run_flow(Patch2SelfFlow())
