#!C:\Users\pacif\OneDrive\Desktop\projects\img_color_reader\public\.env\Scripts\python.exe

from dipy.workflows.flow_runner import run_flow
from dipy.workflows.align import SynRegistrationFlow

if __name__ == "__main__":
    run_flow(SynRegistrationFlow())
